# Generated by Django 6.1.1 on 2026-10-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Imagen del Proyecto')),
                ('tech_stack', models.CharField(max_length=200, verbose_name='Tecnologías (ej: Python, Django, Tailwind)')),
                ('repo_url', models.URLField(blank=True, null=True, verbose_name='Enlace al Repositorio (GitHub)')),
                ('live_url', models.URLField(blank=True, null=True, verbose_name='Enlace a Demo/Sitio en vivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
