# Generated by Django 6.1.1 on 2026-10-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1, help_text='Orden de la lección en el curso')),
                ('video_url', models.URLField(blank=True, help_text='Enlace de YouTube o Vimeo', null=True)),
                ('content', models.TextField(blank=True, help_text='Explicación, ejercicios o código de la lección')),
                ('is_free_preview', models.BooleanField(default=False, help_text='¿Es una vista previa gratuita?')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
